// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfd5m6CC3r2bhyUA1vkPR-7KybflveZX0',
    appId: '1:1272580441:web:c66004a88ac12969376448',
    messagingSenderId: '1272580441',
    projectId: 'script-siamna',
    authDomain: 'script-siamna.firebaseapp.com',
    storageBucket: 'script-siamna.appspot.com',
    measurementId: 'G-9PLCZ2Y12L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIG7p3CZboO14EHZtUtxgcsU3vhVZ0V1M',
    appId: '1:1272580441:android:8b8674d596d1143f376448',
    messagingSenderId: '1272580441',
    projectId: 'script-siamna',
    storageBucket: 'script-siamna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAP_tjSFNDiX3s-dzn9ZcMI_1RVgzt8GM',
    appId: '1:1272580441:ios:1087ccce9a638473376448',
    messagingSenderId: '1272580441',
    projectId: 'script-siamna',
    storageBucket: 'script-siamna.appspot.com',
    iosBundleId: 'com.example.flutterScriptSiamna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAP_tjSFNDiX3s-dzn9ZcMI_1RVgzt8GM',
    appId: '1:1272580441:ios:fc4be979ec8f8676376448',
    messagingSenderId: '1272580441',
    projectId: 'script-siamna',
    storageBucket: 'script-siamna.appspot.com',
    iosBundleId: 'com.example.flutterScriptSiamna.RunnerTests',
  );
}
